name: airline_review_app
description: A professional airline review app with clean architecture
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Networking
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Dependency Injection
  get_it: ^7.6.4

  # UI & Utils
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  intl: ^0.18.1

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true