// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAH6oGceTZ9_HTT0tyE3wLnoPK7WZWHsI',
    appId: '1:1016001027287:web:020a34ee5c6dfc36bc6492',
    messagingSenderId: '1016001027287',
    projectId: 'airline-3da39',
    authDomain: 'airline-3da39.firebaseapp.com',
    storageBucket: 'airline-3da39.firebasestorage.app',
    measurementId: 'G-C9HS1JRBC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFXSusegp-9lkE4hVLexgTFhHXrfWvvNc',
    appId: '1:1016001027287:android:d67be7580c7a588dbc6492',
    messagingSenderId: '1016001027287',
    projectId: 'airline-3da39',
    storageBucket: 'airline-3da39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkv3alxHS6Zr5uS_V3A-Ptj4F4qxmBL4U',
    appId: '1:1016001027287:ios:99c8eca294b7aa68bc6492',
    messagingSenderId: '1016001027287',
    projectId: 'airline-3da39',
    storageBucket: 'airline-3da39.firebasestorage.app',
    iosBundleId: 'com.example.airlineReviewApp',
  );
}
